<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="8845" started-at="2017-01-05T07:44:24Z" finished-at="2017-01-05T07:44:33Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="8845" started-at="2017-01-05T07:44:24Z" finished-at="2017-01-05T07:44:33Z">
      <class name="cn.celloud.Case.Celloud_case">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:cn.celloud.Case.Celloud_case@8373b5c]" name="beforeTest" is-config="true" duration-ms="53" started-at="2017-01-05T15:44:24Z" finished-at="2017-01-05T15:44:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass(java.lang.String)[pri:0, instance:cn.celloud.Case.Celloud_case@8373b5c]" name="beforeClass" is-config="true" duration-ms="4" started-at="2017-01-05T15:44:24Z" finished-at="2017-01-05T15:44:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:cn.celloud.Case.Celloud_case@8373b5c]" name="beforeMethod" is-config="true" duration-ms="3709" started-at="2017-01-05T15:44:25Z" finished-at="2017-01-05T15:44:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="login_case(java.lang.reflect.Method)[pri:0, instance:cn.celloud.Case.Celloud_case@8373b5c]" name="login_case" duration-ms="3675" started-at="2017-01-05T15:44:28Z" finished-at="2017-01-05T15:44:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void cn.celloud.Case.Celloud_case.login_case(java.lang.reflect.Method) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at cn.celloud.Case.Celloud_case.login_case(Celloud_case.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_case -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:cn.celloud.Case.Celloud_case@8373b5c]" name="afterMethod" is-config="true" duration-ms="1366" started-at="2017-01-05T15:44:32Z" finished-at="2017-01-05T15:44:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:cn.celloud.Case.Celloud_case@8373b5c]" name="afterClass" is-config="true" duration-ms="0" started-at="2017-01-05T15:44:33Z" finished-at="2017-01-05T15:44:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- cn.celloud.Case.Celloud_case -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
